version: "3"

services:
    app:
        container_name: app
        #image: cake-app
        build: ./docker  
        volumes:
           - ./static:/app/static   
           - .:/app
           - ./nginx.conf:/etc/nginx/nginx.conf     
        ports:
            - "8082:8080"
